# Generated by Django 4.1.7 on 2023-03-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_type', models.CharField(choices=[('Psychologist', 'Psychologist'), ('Psychiatrist', 'Psychiatrist'), ('Therapist', 'Therapist'), ('Counsellor', 'Counsellor'), ('Clinical Social Worker', 'Clinical Social Worker')], max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('edu_type', models.CharField(choices=[('Psychologist', 'Psychologist'), ('Psychiatrist', 'Psychiatrist'), ('Therapist', 'Therapist'), ('Counsellor', 'Counsellor'), ('Clinical Social Worker', 'Clinical Social Worker')], max_length=30)),
                ('license', models.CharField(max_length=100)),
                ('nid_pass', models.CharField(max_length=100)),
            ],
        ),
    ]
