# Generated by Django 4.1.7 on 2023-03-21 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_patient_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='nid_pass',
            new_name='nid_passport',
        ),
    ]
